### PR TITLE
Added locales for export config yaml error messages.

### PR DESCRIPTION
**Pull request by manwithtwowatches**

### CODE REVIEW

**Comment by ulferts** [comment]
Not sure if it is related to this PR (could also be in https://www.openproject.org/work_packages/3497) but inserting only 

<pre>
blubs:
</pre>

into the rows field results in a 500 response.

**Comment by ulferts** [comment]
record.errors[:rows] << "YAML error: #{e.message}"

in export_card_configuration.rb is still missing localization.

**Comment by manwithtwowatches** [comment]
By that point the error message must have already been localised. That's the idea anyway.

**Comment by ulferts** [comment]
yes but the "YAML error: " part is never localised

**Comment by manwithtwowatches** [comment]
ah ok. i assumed that would be the same in german. but yes i'll put it into the locales.

**Pull request merged**
