### PR TITLE
User enforced row heights

### PR DESCRIPTION
**Pull request by manwithtwowatches**
Config file can now have a "height" property for a row which ensures a certain number of pixels.

### CODE REVIEW

**Comment by ulferts** [comment]
Is there a chance I can assign a height to groups as well?

Documentation is missing so I had a hard time trying to figure out what a height of "200" means compared to height of "10".

**Comment by manwithtwowatches** [comment]
Having group heights doesn't fit nicely into the way that i wrote the algorithm. I can change it if it's a hard requirement but I was hoping that I could get away without it.

**Comment by ulferts** [comment]
As of now, it is no hard requirement. Let's see if that changes.

**Comment by manwithtwowatches** [comment]
Also the heights are in pixels. Is that ok or was it intended to be percentages of the card?

**Comment by ulferts** [comment]
As the font size is in px too, I believe that is a good way to go. But it will need to be documented.

Do I understand it correctly that the height is ignored if the font_size is larger than the height (which I find reasonable)?

**Comment by manwithtwowatches** [comment]
No. Just now the height has the highest priority, so it's the font_size which will get ignored.

**Comment by ulferts** [comment]
Will merge once documentation exists.

**Pull request closed without merging**
